#设置注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册中心单机模式
      defaultZone: http://localhost:7001/eureka
      #注册中心集群模式
      #defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    # 設置eureka databoard中 status的名字：规范名字，否则 默认的应该是 ip域名 + springApplicationAame + port
    instance-id: freshadmin001
    # 显示真实节点的ip用于线上定位调试
    prefer-ip-address: true
feign:
  client:
    config: #这里其实下面是设置了一个map  key: default  value 就是实例对象中的各种属性，要熟悉这个套路哈~
      default:
        connectTimeout: 5000
        readTimeout: 50000
  hystrix:
    enabled: true
logging:
  level:
    com.wyz.freshshop.admin.rpcclient.UserAuthClient: info
spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.80.129
                port: 5672
                username: wyz
                password: 123123
      bindings:
        input:
          destination: testExchange
          content-type: application/json
          binder: defaultRabbit
          group: admin001 # 解决重复消费问题 新增消费组
  rabbitmq:
    host: 192.168.80.129
    port: 5672
    username: wyz
    password: 123123
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.129:3306/freshshop?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root-password
  zipkin:
    base-url: http://192.168.80.129:9411/ # 指定zipkin地址
  sleuth:
    sampler:
      # 0 ~ 1 1表示全部采集
      probability: 1