server:
  port: 7001
eureka:
  instance:
    # 这里用localhost，也可以用域名/IP
    hostname: 127.0.0.1
  client:
    # 是否注册到Eureka服务器，server端禁用此选项
    register-with-eureka: false
    # 此客户端是否应从 eureka 服务器获取 eureka 注册表信息。 客户端服务需要拉取所有注册的信息用于rpc，但是作为注册服务器来说不需要此功能，本身就是注册中心了。
    fetch-registry: false
    service-url:
      # 服务注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka # 单机模式指向自己
      #集群模式指向其他的Eureka节点
      #defaultZone: http://localhost:7002/eureka
  server:
    enable-self-preservation: false # 不启用服务保护，与下面的配置配合的效果就是 2秒没心跳 立马删掉服务信息
    eviction-interval-timer-in-ms: 2000 # 2秒就扫描一次