# \u4F7F\u7528Nacos\u4EE5\u540E \u8FD9\u4E2A\u914D\u7F6E\u5C31\u4F1A\u4ECE\u914D\u7F6E\u4E2D\u5FC3\u53BB\u62C9\u53D6dev\u7684\u914D\u7F6E\u6587\u4EF6 \u800C\u4E0D\u662F\u9879\u76EE\u672C\u5730\u7684dev\u73AF\u5883
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      # 服务注册
      discovery:
        server-addr: 192.168.80.129:1111
    sentinel:
      transport:
        dashboard: 192.168.80.129:8080
        port: 8719
# springboot actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"